### ISSUE TITLE
パスワードの変更に失敗するとハンドリングされていないエラーがでる

### ISSUE THREAD

**Issue by hsano333** [M1n01/ft_transcendence#169]
次のエラーはたぶんハンドリングされていないエラーなので対応が必要
```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

![image](https://github.com/user-attachments/assets/a50e674a-22be-4ae4-a40b-2d40435b5941)

**Comment by hno-guchi** [comment]
似たような現象を確認しました。
（こちらは、変更ボタンを２回連続でクリックすると発生しました。）

原因：[frontend/src/users/js/users.js]:35　「if (response.error) return;」
修正：if (!response || response.error) return;とすることで対応しました
<img width="1792" alt="スクリーンショット 2024-10-24 16 27 43" src="https://github.com/user-attachments/assets/2f501027-8d00-4050-aae1-ab8b3d3b3bef">

**Comment by hsano333** [comment]
ここだけでなく、Djangoからデータを引っ張ってくるヶ所で、if(response.error)としているが、responseがない場合(null)に発生するので、const res = { error: true, status: 500 };を返すことで対応する。

**Comment by hsano333** [comment]
#178 で対応
