### ISSUE TITLE
トーナメント詳細ページのconsole error

### ISSUE THREAD

**Issue by M1n01** [M1n01/ft_transcendence#172]
ブレークポイントで確認した結果、`TounamenttChart.js`の91行目next_game_data1がundefinedの時があるようです。

![Screenshot 2024-10-24 at 16 12 30](https://github.com/user-attachments/assets/0a4c53cd-01d6-409b-bae6-203d86b9dbf1)

**Comment by hsano333** [comment]
ありがとうございます。
確認します

**Comment by hsano333** [comment]
次のプルリクで修正します

**Comment by hsano333** [comment]
#178 で対応
