### ISSUE TITLE
【Mandatory】SPA【Module】

### ISSUE THREAD

**Issue by M1n01** [M1n01/ft_transcendence#2]

**Comment by hsano333** [comment]
- [ ] SSR対応
- [ ] ルーティング
- [ ] 履歴（戻る、進むボタン）
- [ ] キャッシュの利用

**Comment by hsano333** [comment]
- [x] SSRの対応
- [x] ルーティング
- [x] キャッシュの利用
- [x] 「戻る」「進む」ボタン対応
- [x] スクリプトタグがどんどん増えていく不具合修正

**Comment by hsano333** [comment]
42OAuth対応時にある程度の不具合は対応（コードが汚いので多少整理は必要かも）
基礎的な作りとしては完了
問題点や対応箇所が必要なら別途イシューを発行する
