### ISSUE TITLE
logがコンテナ立ち上げ時に作られない

### ISSUE THREAD

**Issue by hsano333** [M1n01/ft_transcendence#71]

**Comment by hsano333** [comment]
logディレクトリを作成した対応
空ディレクトリはgitに上げあれないので、'_'ファイルを作成した

**Comment by M1n01** [comment]
@hsano333 
こちら.gitkeepの方が適切かと思います！

https://zenn.dev/shuichi/articles/git-check-in-empty-directory

**Comment by hsano333** [comment]
@M1n01 
情報ありがとうございます
.gitkeepに変更しました
